### ISSUE TITLE
The name is inaccurate

### ISSUE THREAD

**Issue by chocolateboy** [twolfson/function-to-string#2]
First of all, thanks for this! I've spotted a couple of other projects on npm that purport to do the same thing, but they use regexes that are trivial to break (e.g. [with comments](https://github.com/regexps/function-regex)).

I realize it's hard to come up with sensible names given npm's [naming policy](https://github.com/npm/npm/issues/798), but "function-to-string" is inaccurate (it returns an object rather than a string, and it sounds redundant since [`Function.toString`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/toString) is built-in) and doesn't help with discoverability. [`parse-function`](https://www.npmjs.com/package/parse-function) isn't available, but e.g. `function-parser` is.

**Comment by twolfson** [comment]
Names are always tricky. When weighing breaking people's dependencies vs a rename I think `function-to-string` does encapsulates the concept good enough.

Fwiw, discovery is usually best done via `keywords` not the package name itself:

https://github.com/twolfson/function-to-string/blob/0.2.0/package.json#L41-L48

**Comment by chocolateboy** [comment]
> Fwiw, discovery is usually best done via keywords not the package name itself

FYI:

```
$ cat ./nsk
#!/bin/bash
exec node ./npm-keyword-search/index.js "$@" | tr -s ' ' ' '
```

```
$ nsk function | wc -l
280

$ nsk parse | wc -l
488

$ nsk function parse | wc -l
7

$ nsk function parser | wc -l
3

$ nsk function parsing | wc -l
2

$ nsk function parse | grep function-to-string | wc -l
0

$ nsk function parser | grep function-to-string | wc -l
0

$ nsk function parsing | grep function-to-string | wc -l
0
```

**Comment by twolfson** [comment]
Having poor keywords is not a valid reason to rename the package (comparable to throwing the baby out with the bathwater). Feel free to open a PR that adds keywords like `parse`.
